### ISSUE TITLE
not able to build

### ISSUE THREAD

**Issue by ekg** [vgteam/libbdsg-easy#4]
For me this is broken (tested a4473db21058047c940a07a1f818c006e3e4a74f).

I think that the right fix is adding cmake to lbbdsg source repo.

**Comment by jeizenga** [comment]
Hmm. It works for me locally (on Mac), but I just tried it on courtyard and it seems to be broken there too. I have no issue with moving the cmake, but I don't know if I understand cmake enough to spearhead that.

**Comment by jeizenga** [comment]
Okay, I've made a change in the makefile that should allow this to compile on Linux again, although I am a bit confused why it wasn't working. I'm still on board with moving to cmake, although FWIW I also think we can save some of the organization/software engineering bits like the until after submitting the paper.
